fruits = set(['avocado','tomato','banana'])
vegetables = set(['beets','carrots','tomato'])
print "Fruit set : {}".format(fruits)
print "Vegetables set : {}".format(vegetables)
print "Intersection : {}".format(fruits & vegetables)
print "Union : {}".format(fruits | vegetables)
print "Fruits but not vegetables : {}".format(fruits - vegetables)
print "Vegetables but not fruits : {}".format(vegetables - fruits)
